apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-smithcf
spec:
  selector:
    matchLabels:
      app: webserver-smithcf
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver-smithcf
    spec:
      containers:
      - name: webserver-smithcf
        image: jindego/webserver_smithcf
        imagePullPolicy: Always
        ports:
        - containerPort: 80