apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
spec:
  selector:
    matchLabels:
      app: capstone-webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: capstone-webserver
    spec:
      containers:
      - name: capstone-webserver
        image: jindego/webserver_smithcf
        ports:
        - containerPort: 80