apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver_smithcf
spec:
  selector:
    matchLabels:
      app: webserver_smithcf
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver_smithcf
    spec:
      containers:
      - name: webserver_smithcf
        image: jindego/webserver_smithcf
        ports:
        - containerPort: 80