
version: 2.1

jobs:
  build-frontend:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get -y -qq update
            apt-get -y install sudo
            sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" -y
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      - run:
          name: build image
          command: |
            docker build -t webserver_smithcf .
            docker image ls

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build-frontend