version: 2.1

jobs:
  build-frontend:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            # install sudo package 
            apt-get -y -qq update
            apt-get -y install sudo

            # install dependencies to install docker
            sudo apt-get -y install curl gnupg2 software-properties-common

            # Install Docker
            curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" -y
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # Required for using docker commands in CircleCI
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      - run:
          name: build image
          command: |
            docker build -t webserver_smithcf .
            docker image ls

      - run:
          name: push image
          command: |
            docker login -u "jindego" -p "$dockerpass"
            docker tag webserver_smithcf jindego/webserver_smithcf
            docker push jindego/webserver_smithcf


  deploy-change-to-kube:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            # install sudo package 
            apt-get -y -qq update
            apt-get -y install sudo

            # install curl
            sudo apt-get -y install curl gnupg2 software-properties-common

            # install AWS CLI at latest version
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            
            # Install kubectl
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            
            # Install eksctl
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            

      - run:
          name: Print versions
          command: |
            # Get versions
            awsversion=$(aws --version)
            kubectlclientversion=$(kubectl version --client)
            eksctlversion=$(eksctl version)

            # Print versions of installed utils
            echo "AWS CLI version"
            echo $awsversion
            echo ""
            echo "kubectl version"
            echo $kubectlclientversion
            echo ""
            echo "eksctl version"
            echo $eksctlversion

      - run:
          name: build kube cluster
          command: |
            # eksctl create cluster --name UdacityCapstone --version 1.19 --region $AWS_DEFAULT_REGION --nodegroup-name UdacityCapstone --node-type t3.nano --nodes-min 2 --nodes-max 4 --managed
            aws cloudformation list-exports

workflows:
  default:
    jobs:
      # - build-frontend
      - deploy-change-to-kube
            # requires: [build-frontend]